M48
; DRILL file {KiCad 8.0.4-8.0.4-0~ubuntu22.04.1} date 2024-08-03T19:16:44+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-03T19:16:44+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4-8.0.4-0~ubuntu22.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X5.5Y-3.8
X5.5Y-3.9
X5.5Y-4.0
X5.5Y-4.1
X5.6Y-3.8
X5.6Y-3.9
X5.6Y-4.0
X5.6Y-4.1
M30
