M48
; DRILL file {KiCad 8.0.4-8.0.4-0~ubuntu22.04.1} date 2024-08-03T19:16:44+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-03T19:16:44+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4-8.0.4-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
%
G90
G05
T1
X6.05Y-3.25
X6.05Y-3.65
X6.05Y-4.05
M30
