[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags = [
    # "-C",
    # "target-feature=+crt-static",
    # для tokio-console
    "--cfg",
    "tokio_unstable",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    # для tokio-console
    "--cfg",
    "tokio_unstable",
]
