M48
; DRILL file {KiCad 8.0.4-8.0.4-0~ubuntu22.04.1} date 2024-08-10T20:12:59+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-10T20:12:59+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4-8.0.4-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1083
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.0709Y-2.7165
X2.0709Y-5.0
X4.0Y-2.7165
X4.0Y-5.0
T2
X1.75Y-2.15
X4.75Y-2.15
X4.75Y-5.75
M30
