M48
; DRILL file {KiCad 8.0.4-8.0.4-0~ubuntu22.04.1} date 2024-08-07T21:26:23+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-07T21:26:23+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4-8.0.4-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.75Y-2.15
X4.75Y-2.15
X4.75Y-5.75
M30
