M48
; DRILL file {KiCad 8.0.7-8.0.7-0~ubuntu24.04.1} date 2025-01-20T15:28:16+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-20T15:28:16+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7-8.0.7-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1043
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X-0.2Y1.4
X-0.2Y-1.4
T2
X-1.811Y1.811
X-1.811Y-1.811
X0.4724Y1.811
M30
