M48
; DRILL file {KiCad 8.0.3-8.0.3-0~ubuntu22.04.1} date 2024-08-08T09:54:03+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-08T09:54:03+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3-8.0.3-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.75Y-0.15
X3.75Y-0.15
X3.75Y-3.75
M30
