M48
; DRILL file {KiCad 8.0.3-8.0.3-0~ubuntu22.04.1} date 2024-10-22T15:42:30+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-22T15:42:30+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3-8.0.3-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1299
%
G90
G05
T1
X4.0535Y-3.3037
X4.0535Y-4.3982
M30
