M48
; DRILL file {KiCad 8.0.3-8.0.3-0~ubuntu22.04.1} date 2024-08-09T14:04:43+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-09T14:04:43+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3-8.0.3-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1043
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.1Y-4.9
X2.4Y-2.7
X2.4Y-3.4
T2
X1.75Y-2.15
X4.75Y-2.15
X4.75Y-5.75
M30
