"" = [["PMCNV-AI4T", 13], ["PMCNV-INA226x4", 4], ["PMCPU-LLU", 1], ["PMDBG-FFC20", 1]]
" C_1uF_16V_0603_MLCC-X7R " = [["PMCNV-AI4T", 6], ["PMCNV-AI4W", 1], ["PMCNV-AI8IU", 3], ["PMCNV-Count6", 2], ["PMIFC-1Wire", 1], ["PMIFC-1Wx12", 2], ["PMMCU-ESP32C3", 2]]
" C_4.7uF_16V_0805_MLCC-X7R" = [["PMCNV-AI4T", 1], ["PMCNV-AI4W", 1], ["PMCNV-AI8IU", 1], ["PMIFC-1Wx12", 1]]
"0217001.MXP" = [["PMPS-20W", 2]]
"15EDGK-3.5-03P" = [["PMCNV-DIx16", 1], ["PMCNV-DIx32", 1], ["PMCNV-DQx16", 1], ["PMCNV-PWMx16", 1], ["PMPS-20W", 1]]
"15EDGK-3.5-04P" = [["PMCPU-LLP", 3]]
"15EDGK-3.5-05P" = [["PMCNV-AI8IU", 1], ["PMCNV-Count6", 1], ["PMCPU-LLP", 1], ["PMCPU-LLU", 1], ["PMMCU-ESP32CAN", 1], ["PMPS-20W", 2], ["PM_CPU-RP", 1]]
"15EDGK-3.5-08P" = [["PMCNV-AIWx4", 4], ["PMCNV-DIx16", 2], ["PMCNV-DIx32", 2], ["PMCNV-DQx16", 2], ["PMCNV-PWMx16", 2]]
"15EDGK-3.5-10P" = [["PMCNV-Count6", 2]]
"15EDGKC-3.5-03P" = [["PMCNV-RQx8", 1]]
"15EDGKC-3.5-04P" = [["PMIFC-I2Cx8", 8]]
"15EDGKC-3.5-08P" = [["PMCNV-RQx8", 2]]
"15EDGKNH-3.5-10P" = [["PMMCU-ESP32C3", 1], ["PM_CPU-RP", 1]]
"15EDGKNH-3.5-14P" = [["PMCNV-AI4W", 2]]
"15EDGKNH-3.5-16P" = [["PMCNV-AI8IU", 2]]
"15EDGRC-3.5-03P" = [["PMCNV-AIWx4", 1], ["PMCNV-DIx16", 1], ["PMCNV-DIx32", 1], ["PMCNV-DQx16", 1], ["PMCNV-INA226x4", 4], ["PMCNV-PWMx16", 1], ["PMCNV-RQx8", 1], ["PMIFC-I2Cx8", 1], ["PMPS-20W", 1]]
"15EDGRC-3.5-04P" = [["PMCPU-LLP", 3]]
"15EDGRC-3.5-05P" = [["PMCNV-AI8IU", 1], ["PMCNV-Count6", 1], ["PMCPU-LLP", 1], ["PMCPU-LLU", 2], ["PMMCU-ESP32CAN", 1], ["PMPS-20W", 2], ["PM_CPU-RP", 1]]
"15EDGRC-3.5-08P" = [["PMCNV-DIx16", 2], ["PMCNV-DQx16", 2], ["PMCNV-PWMx16", 2], ["PMCNV-RQx8", 2]]
"15EDGRC-3.5-10P" = [["PMCNV-AI4T", 1], ["PMCNV-Count6", 2]]
"15EDGRH-3.5-06P" = [["PMIFC-1Wire", 6], ["PMIFC-1Wx12", 6]]
"15EDGRH-3.5-10P" = [["PMIFC-I2Cx8", 4]]
"15EDGRH-3.5-16P" = [["PMCNV-AIWx4", 2], ["PMCNV-DIx32", 2]]
"15EDGRHC-THR-3.5-10P" = [["PMMCU-ESP32C3", 1], ["PM_CPU-RP", 1]]
"15EDGRHC-THR-3.5-14P" = [["PMCNV-AI4W", 2]]
"15EDGRHC-THR-3.5-16P" = [["PMCNV-AI8IU", 2]]
2N7002K = [["PMCNV-DQx16", 1], ["PMIFC-1Wire", 1]]
64900001039 = [["PMCNV-DQx16", 1], ["PMPS-20W", 2], ["PM_CPU-RP", 1]]
AD7193BRUZ = [["PMCNV-AI4T", 1], ["PMCNV-AI4W", 1], ["PMCNV-AIWx4", 1]]
ADS8688 = [["PMCNV-AI8IU", 1]]
AFA07-S06FCC-00 = [["PMCPU-LLU", 1], ["PMHMI-Bx12Lx8", 1]]
AFA07-S12FCC-00 = [["PMCNV-AI4W", 1], ["PMCNV-Count6", 1], ["PMCNV-DIx16", 2], ["PMCNV-DIx32", 4], ["PMCNV-RQx8", 1], ["PMCPU-LLP", 1], ["PMCPU-LLU", 1], ["PMLED-10", 1], ["PMLED-18", 2], ["PMMCU-ESP32C3", 1], ["PMMCU-ESP32CAN", 1], ["PMPS-20W", 1], ["PM_CPU-RP", 3], ["PM_DBG-FFC", 2], ["PM_HMI-Keyboard", 2], ["PM_HMI-Touch", 1]]
AFA07-S20FCC-00 = [["PMCNV-AI4T", 2], ["PMCNV-AI4W", 2], ["PMCNV-AI8IU", 2], ["PMCNV-AIWx4", 1], ["PMCNV-Count6", 2], ["PMCNV-DIx16", 1], ["PMCNV-INA226x4", 1], ["PMCNV-PWMx16", 1], ["PMCNV-RQx8", 1], ["PMCPU-LLU", 2], ["PMDBG-FFC20", 2], ["PMIFC-1Wx12", 2], ["PMIFC-I2Cx8", 1], ["PMMCU-ESP32C3", 1], ["PMMCU-ESP32CAN", 1]]
AFA11-S06GLA-00 = [["PMCPU-LLP", 1]]
AFA11-S12GLA-00 = [["PMCNV-AIWx4", 1], ["PMCNV-DIx16", 2], ["PMCNV-DIx32", 4], ["PMCNV-DQx16", 2], ["PMCNV-PWMx16", 2], ["PMCNV-RQx8", 1], ["PMPS-20W", 1]]
AFA11-S20GLA-00 = [["PMCNV-AIWx4", 1], ["PMCNV-DIx16", 1], ["PMCNV-DIx32", 2], ["PMCNV-DQx16", 2], ["PMCNV-INA226x4", 1], ["PMCNV-PWMx16", 1], ["PMCNV-RQx8", 1], ["PMCPU-LLP", 2], ["PMIFC-1Wire", 2], ["PMIFC-I2Cx8", 1], ["PMPS-20W", 2]]
B0503S-2W = [["PMIFC-1Wire", 1], ["PMIFC-1Wx12", 1]]
B0505LS-1W = [["PMCNV-AI4T", 1], ["PMCNV-AI4W", 1], ["PMCNV-AI8IU", 1], ["PMCNV-AIWx4", 1], ["PMCNV-DQx16", 1], ["PMCNV-INA226x4", 1], ["PMCNV-PWMx16", 1], ["PMIFC-I2Cx8", 1]]
B2405LS-1WR3 = [["PMMCU-ESP32C3", 1], ["PMMCU-ESP32CAN", 1]]
B2405S-2WR3 = [["PMCNV-RQx8", 1]]
B5819W = [["PMCPU-LLP", 1], ["PMCPU-LLU", 1]]
BS-12-A1AJ002-F = [["PMCPU-LLP", 1], ["PMCPU-LLU", 1], ["PM_CPU-RP", 1]]
CA-IS3021G = [["PMCNV-DQx16", 1], ["PMCNV-INA226x4", 1], ["PMCNV-PWMx16", 1], ["PMIFC-1Wire", 1], ["PMIFC-1Wx12", 1], ["PMIFC-I2Cx8", 1]]
CA-IS3062VW = [["PMCPU-LLP", 2], ["PMCPU-LLU", 2], ["PMMCU-ESP32C3", 1], ["PMMCU-ESP32CAN", 1]]
CA-IS3098W = [["PMCPU-LLP", 2], ["PMCPU-LLU", 1], ["PM_CPU-RP", 1]]
CA-IS3741HW = [["PMCNV-AI4W", 1], ["PMCNV-AI8IU", 1], ["PMCNV-AIWx4", 1]]
CA-IS3761HW = [["PMCNV-AI4T", 1]]
CA-IS3980P = [["PMCNV-DIx16", 2], ["PMCNV-DIx32", 4]]
CA-IS3988P = [["PMCNV-Count6", 1]]
"CDSOT23-SM712  " = [["PMCPU-LLP", 2], ["PMCPU-LLU", 1]]
"CJA1117B-3.3" = [["PMMCU-ESP32C3", 1], ["PMMCU-ESP32CAN", 1]]
C_100nF_100V_0603_MLCC-X7R = [["PMCNV-AIWx4", 6], ["PMCNV-DIx16", 1], ["PMCNV-DIx32", 2], ["PMCNV-DQx16", 3], ["PMCNV-INA226x4", 6], ["PMCNV-PWMx16", 3], ["PMCNV-RQx8", 1], ["PMCPU-LLP", 8], ["PMIFC-1Wire", 2], ["PMIFC-I2Cx8", 3]]
C_100nF_16V_0603_MLCC-X7R = [["PMCNV-AI4T", 6], ["PMCNV-AI4W", 6], ["PMCNV-AI8IU", 2], ["PMCPU-LLU", 6], ["PMHMI-Bx12Lx8", 1], ["PMIFC-1Wx12", 2], ["PMMCU-ESP32C3", 2], ["PMMCU-ESP32CAN", 2], ["PM_CPU-RP", 2]]
C_10nF_100V_0603_MLCC-X7R = [["PMCNV-AIWx4", 6]]
C_10nF_16V_0603_MLCC-X7R = [["PMCNV-AI4W", 6]]
C_10nF_50V_0603_MLCC-C0G = [["PMCNV-AI8IU", 8]]
C_10uF_16V_0805_MLCC-X5R = [["PM_CPU-RP", 3]]
C_10uF_16V_0805_MLCC-X7R = [["PMCNV-AI4T", 1], ["PMCNV-AI4W", 1], ["PMCNV-AI8IU", 3], ["PMCNV-Count6", 1], ["PMCPU-LLU", 6], ["PMIFC-1Wx12", 2], ["PMMCU-ESP32C3", 4], ["PMMCU-ESP32CAN", 4]]
C_10uF_50V_1206_MLCC-X7R = [["PMCNV-AIWx4", 2], ["PMCNV-DQx16", 2], ["PMCNV-INA226x4", 2], ["PMCNV-PWMx16", 2], ["PMCNV-RQx8", 1], ["PMCPU-LLP", 8], ["PMIFC-1Wire", 3], ["PMIFC-I2Cx8", 3]]
C_1nF_100V_0603_MLCC-X7R = [["PMCNV-AIWx4", 8]]
C_1nF_16V_0603_MLCC-X7R = [["PMCNV-AI4W", 8]]
C_1nF_50V_0603_MLCC-X7R = [["PMCNV-AI4T", 8]]
C_1uF_50V_0603_MLCC-X7R = [["PMCNV-AIWx4", 1], ["PMCNV-RQx8", 1], ["PMCPU-LLP", 4], ["PMCPU-LLU", 4], ["PMIFC-1Wire", 1], ["PMMCU-ESP32C3", 3], ["PMMCU-ESP32CAN", 5]]
"C_2.2nF_50V_0603_MLCC-X7R" = [["PMCNV-Count6", 6]]
C_22nF_25V_0603_MLCC-X7R = [["PMCNV-AI4T", 4]]
C_22uF_16V_0805_MLCC-X5R = [["PMMCU-ESP32C3", 1], ["PMMCU-ESP32CAN", 1]]
C_22uF_16V_1210_MLCC-X7R = [["PMCNV-AI8IU", 1]]
C_22uF_25V_1210_MLCC-X7R = [["PMPS-20W", 3]]
C_22uF_50V_2220_MLCC-X7R = [["PMPS-20W", 3], ["PM_CPU-RP", 4]]
"C_4.7nF_2kV_1812" = [["PMCNV-AI8IU", 1]]
"C_4.7nF_2kV_1812_MLCC-X7R" = [["PMCNV-RQx8", 1], ["PMCPU-LLP", 1], ["PMCPU-LLU", 1], ["PMPS-20W", 1], ["PM_CPU-RP", 1]]
DS3231SN = [["PMCPU-LLP", 1], ["PMCPU-LLU", 1], ["PM_CPU-RP", 1]]
ESDCAN05-2BWY = [["PMCPU-LLP", 2], ["PMCPU-LLU", 2], ["PMMCU-ESP32CAN", 1]]
ESP32-C3-WROOM-02U-N4 = [["PMCNV-Count6", 1], ["PMIFC-1Wire", 1], ["PMIFC-1Wx12", 1], ["PMMCU-ESP32C3", 1], ["PMMCU-ESP32CAN", 1]]
"FB_300mΩ_1kΩ@100MHz_1206" = [["PMCNV-AI4T", 1], ["PMCNV-AI4W", 1], ["PMCNV-AIWx4", 1]]
"FFC_10P_P1.0_50mm_reverse" = [["PMCNV-AI4W", 1], ["PMCNV-AIWx4", 1]]
"FFC_12P_P1.0_100mm_straight" = [["PMCNV-AI4W", 1], ["PMCNV-AIWx4", 1], ["PMCNV-DIx16", 2], ["PMCNV-DIx32", 4], ["PMCNV-RQx8", 1], ["PMCPU-LLP", 1], ["PMCPU-LLU", 1], ["PM_CPU-RP", 1], ["PM_HMI-Keyboard", 1]]
"FFC_12P_P1.0_50mm_reverse" = [["PMPS-20W", 1]]
"FFC_20P_P1.0_50mm_straight" = [["PMCNV-RQx8", 1], ["PMPS-20W", 1]]
G5NB-1A-E-DC5 = [["PMCNV-RQx8", 8]]
IRM-20-24 = [["PMPS-20W", 1]]
K7803-2000R3 = [["PMPS-20W", 1], ["PM_CPU-RP", 1]]
K7805-2000R3 = [["PMPS-20W", 2], ["PM_CPU-RP", 1]]
Keystone_5117 = [["PMCNV-AI4T", 2], ["PMCNV-AI4W", 2], ["PMCNV-AI8IU", 2], ["PMCNV-AIWx4", 2], ["PMCNV-DQx16", 2], ["PMCNV-INA226x4", 2], ["PMCNV-PWMx16", 2], ["PMIFC-1Wire", 2], ["PMIFC-1Wx12", 2], ["PMIFC-I2Cx8", 2], ["PMMCU-ESP32C3", 2], ["PM_CPU-RP", 1]]
LuckfoxLyraPlus = [["PMCPU-LLP", 1]]
"MCP23017-E/SS" = [["PMCNV-DIx16", 1], ["PMCNV-DIx32", 2], ["PMCNV-RQx8", 1], ["PMHMI-Bx12Lx8", 1]]
"MCP23S17-E/SS" = [["PMCNV-DIx16", 1], ["PMCNV-DQx16", 1], ["PM_HMI-Keyboard", 1]]
PCA9685PW = [["PMCNV-PWMx16", 1]]
"PMLED-10-v0.0.2" = [["PMCNV-AIWx4", 1], ["PMCNV-INA226x4", 1], ["PMCNV-RQx8", 1], ["PMCPU-LLP", 1], ["PMCPU-LLU", 1], ["PMIFC-1Wire", 1], ["PMIFC-1Wx12", 1], ["PMPS-20W", 1]]
"PMLED-18-v0.0.2" = [["PMCNV-DIx16", 1], ["PMCNV-DIx32", 2], ["PMCNV-DQx16", 1], ["PMCNV-PWMx16", 1]]
"PM_LED-10-v0.0.1" = [["PMCNV-AI4T", 1], ["PMCNV-AI4W", 1], ["PMCNV-Count6", 1], ["PMMCU-ESP32C3", 1], ["PMMCU-ESP32CAN", 1], ["PM_CPU-RP", 1]]
"PinHeader_01x03_P2.00_THT_straight" = [["PM_CPU-RP", 1]]
"PinHeader_01x14_P2.54_SMD_straight" = [["PM_DBG-FFC", 1]]
"PinHeader_02x13_P2.54_THT_straight" = [["PM_HMI-Touch", 1]]
"R_0R01_2512_1%_50ppm" = [["PMCNV-INA226x4", 4]]
"R_0R_1206_1%" = [["PMCNV-AI8IU", 8]]
"R_100R_0603_1%" = [["PMCNV-AI4W", 8], ["PMCNV-AIWx4", 8], ["PMCNV-DQx16", 1], ["PMIFC-1Wire", 1]]
"R_10k_0603_1%" = [["PMCNV-AI4T", 2], ["PMCNV-AI4W", 1], ["PMCNV-AIWx4", 1], ["PMCPU-LLP", 1], ["PMCPU-LLU", 1]]
"R_10k_0603x4_1%" = [["PMCNV-Count6", 3], ["PMIFC-1Wire", 1], ["PMIFC-1Wx12", 1], ["PMMCU-ESP32C3", 3], ["PMMCU-ESP32CAN", 3], ["PM_CPU-RP", 1]]
"R_120R_0603_1%" = [["PMCPU-LLP", 4], ["PMCPU-LLU", 3], ["PMMCU-ESP32CAN", 1]]
"R_1R5_0603_1%" = [["PMCNV-AI4T", 1], ["PMCNV-AI4W", 1], ["PMCNV-AIWx4", 1]]
"R_1k69_0603_1%" = [["PMCNV-AI4T", 9]]
"R_1k_0603_1%" = [["PMCNV-AI4W", 7], ["PMCNV-AIWx4", 7], ["PMCNV-Count6", 8], ["PMCPU-LLP", 1], ["PMCPU-LLU", 1], ["PMMCU-ESP32C3", 1], ["PMMCU-ESP32CAN", 1], ["PMPS-20W", 1], ["PM_CPU-RP", 1]]
"R_220R_0603_1%" = [["PMCNV-INA226x4", 1], ["PMCNV-PWMx16", 1], ["PMIFC-I2Cx8", 1]]
"R_220R_0603x4_1%" = [["PMCNV-PWMx16", 4]]
"R_249R_1206_0.1%_25ppm " = [["PMCNV-AI8IU", 8]]
"R_250R_0603_1%" = [["PMCNV-AI4W", 1], ["PMCNV-AIWx4", 1]]
"R_2k7_0603_1%" = [["PMCNV-Count6", 6], ["PMCNV-DIx16", 16]]
"R_2k7_0603x4_1%" = [["PMCNV-DIx32", 8]]
"R_300R_0603_1%" = [["PMCNV-AI4T", 9]]
"R_330R_0603_1%" = [["PMCNV-Count6", 1], ["PMCNV-INA226x4", 2], ["PMCNV-PWMx16", 2], ["PMMCU-ESP32C3", 3], ["PMMCU-ESP32CAN", 3]]
"R_330R_0603x4_1%" = [["PMHMI-Bx12Lx8", 2], ["PMIFC-1Wire", 1], ["PMIFC-1Wx12", 1]]
"R_3k3_0603_1%" = [["PMCNV-DQx16", 2], ["PMIFC-1Wire", 2], ["PMIFC-1Wx12", 2], ["PMMCU-ESP32C3", 2], ["PMMCU-ESP32CAN", 2]]
"R_3k3_0603x4_1%" = [["PMCPU-LLP", 1], ["PMCPU-LLU", 1], ["PMIFC-I2Cx8", 5]]
"R_4k7_0603_1%" = [["PMCPU-LLU", 1], ["PMIFC-1Wire", 1], ["PMIFC-1Wx12", 1], ["PMPS-20W", 1], ["PM_CPU-RP", 1]]
"R_680R_0603_1%" = [["PMCNV-DIx16", 18], ["PMCNV-DIx32", 36], ["PMCNV-DQx16", 18], ["PMCNV-PWMx16", 16], ["PMCNV-RQx8", 10], ["PMCPU-LLP", 7], ["PMCPU-LLU", 6], ["PMMCU-ESP32C3", 3], ["PMMCU-ESP32CAN", 3], ["PMPS-20W", 1], ["PM_CPU-RP", 6]]
"R_680R_0603x4_1%" = [["PMLED-18", 4]]
"R_750R_0603_1%" = [["PMCNV-Count6", 6], ["PMCNV-DIx16", 16]]
"R_750R_0603x4_1%" = [["PMCNV-DIx32", 8]]
SMAJ33CA = [["PMCNV-AI4T", 5], ["PMCNV-AI8IU", 8]]
SN74LVC2G14DBVR = [["PMCNV-AI4W", 1], ["PMCNV-AIWx4", 1], ["PMCNV-DIx16", 1], ["PMCPU-LLP", 1], ["PMCPU-LLU", 1], ["PMMCU-ESP32C3", 1], ["PMMCU-ESP32CAN", 1], ["PM_CPU-RP", 1]]
STWD100NYWY3F = [["PMCPU-LLP", 1], ["PMCPU-LLU", 1], ["PMMCU-ESP32C3", 1], ["PMMCU-ESP32CAN", 1]]
"Shunt 2.54 Open Top" = [["PMDBG-FFC20", 2], ["PM_DBG-FFC", 2]]
Standoff_nylon_M2_nut = [["PMCNV-DIx16", 4], ["PMCNV-DIx32", 8], ["PMCNV-RQx8", 4], ["PMPS-20W", 4]]
Standoff_nylon_M2_screw = [["PMCNV-DIx16", 4], ["PMCNV-DIx32", 8], ["PMCNV-RQx8", 4], ["PMPS-20W", 4]]
Standoff_nylon_M2_shaft_10mm = [["PMCNV-DIx16", 4], ["PMCNV-DIx32", 8], ["PMCNV-RQx8", 4], ["PMPS-20W", 4]]
TAJA106M016RNJ = [["PMCNV-AI4T", 2], ["PMCNV-AI4W", 2], ["PMCNV-AIWx4", 2]]
TBD62783AFG = [["PMCNV-DQx16", 2], ["PMCNV-RQx8", 1]]
TCA9548APWR = [["PMIFC-I2Cx8", 1]]
"TS-1088-AR02016 " = [["PMCNV-Count6", 2], ["PMIFC-1Wire", 2], ["PMIFC-1Wx12", 2], ["PMMCU-ESP32C3", 2], ["PMMCU-ESP32CAN", 2]]
TS-1187A-B-A-B = [["PMHMI-Bx12Lx8", 12], ["PM_HMI-Keyboard", 49]]
"U254-051T-4BH83-S1S " = [["PMCNV-Count6", 1], ["PMIFC-1Wire", 1], ["PMIFC-1Wx12", 1], ["PMMCU-ESP32C3", 1], ["PMMCU-ESP32CAN", 1]]
W25Q32JVSSIQ = [["PM_CPU-RP", 1]]
XL-1606SURC = [["PMCNV-AI4W", 2], ["PMCNV-AIWx4", 2], ["PMCPU-LLP", 1], ["PMCPU-LLU", 1], ["PMMCU-ESP32C3", 1], ["PMMCU-ESP32CAN", 1], ["PM_CPU-RP", 1]]
XL-1606SYGC = [["PMCNV-AI4W", 3], ["PMCNV-AIWx4", 3], ["PMCNV-Count6", 8], ["PMCNV-DIx16", 16], ["PMCNV-DIx32", 32], ["PMCNV-DQx16", 16], ["PMCNV-PWMx16", 16], ["PMCNV-RQx8", 8], ["PMCPU-LLP", 5], ["PMCPU-LLU", 5], ["PMMCU-ESP32C3", 3], ["PMMCU-ESP32CAN", 3], ["PMPS-20W", 3], ["PM_CPU-RP", 5]]
XL-1606UBC = [["PMCNV-AI4W", 2], ["PMCNV-AIWx4", 2], ["PMCNV-DIx16", 2], ["PMCNV-DIx32", 4], ["PMCNV-DQx16", 2], ["PMCNV-RQx8", 2], ["PMCPU-LLP", 2], ["PMCPU-LLU", 2], ["PMMCU-ESP32C3", 2], ["PMMCU-ESP32CAN", 2], ["PM_CPU-RP", 2]]
XL-1608SYGC-06 = [["PMHMI-Bx12Lx8", 8]]
nSMD005 = [["PMCNV-AI8IU", 8]]
